language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.6'
env:
  - DB="POSTGRESQL"
  - DB="MYSQL"
services:
  - mysql
  - postgres
before_install:
  - pip install codecov
  - if [[ $DB = 'POSTGRESQL' ]]; then pip install -q psycopg2; fi
  - if [[ $DB = 'MYSQL' ]]; then pip install -q mysqlclient; fi
install:
  - pip install -e git+https://github.com/tonioo/modoboa.git#egg=modoboa
  - pip install -q factory-boy testfixtures
  - python setup.py -q develop
before_script:
  - if [[ $DB = 'POSTGRESQL' ]]; then psql -c 'create database modoboa_test;' -U postgres; fi
  - if [[ $DB = 'POSTGRESQL' ]]; then psql -c 'create database amavis_test;' -U postgres; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "create database IF NOT EXISTS modoboa_test;" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "create database IF NOT EXISTS amavis_test;" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "CREATE USER 'amavis'@'localhost' IDENTIFIED BY 'amavis'" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'amavis'@'localhost';" -uroot; fi
script:
  - cd test_project
  - coverage run --source ../modoboa_amavis manage.py test modoboa_amavis
after_success:
  - codecov
before_deploy:
  - cd ../modoboa_amavis
  - django-admin compilemessages
  - cd ..
deploy:
  provider: pypi
  user: tonio
  password:
    secure: qtRkmcbA9tbqFw0IK/liCuKszeXDrUC9iI7j3Q4x0jxx7OW8bnn0JqGl45IuKaaSIt1M3PIP0T82h3S+DqBoGfE0xuH4Oe2WwvP76p8afjeOHjoRVOhKihTAZZXsBA2jEteNiDibiu7ezpMXQNaO+BnfYqUJ3ATZJD7xIRNigHo=
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
